services:
  # Service PHP (Le moteur)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs-logs-php
    volumes:
      - .:/var/www/html
    networks:
      - app_network

  # Service Nginx (Le serveur web)
  web:
    image: nginx:alpine
    container_name: cs-logs-web
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network

networks:
  app_network:
    driver: bridge